// migrar.js
import PocketBase from 'pocketbase';
//aqui saca los tipos de typescript para que node lo corra directo
const products = [
  // --- PERROS ---
  {
    name: 'Alimento Perro Adulto',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2340,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 21kg.',
    unit: '21kg',
  },
  {
    name: 'Alimento Cachorro',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2790,
    emoji: '🐶',
    image: '',
    description: 'Fórmula especial para cachorros en crecimiento. Bolsa 15kg.',
    unit: '15kg',
  },
  {
    name: 'Alimento Perro Cachorro Raza Medianas Y Grandes',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2990,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 15kg.',
    unit: '15kg',
  },
  {
    name: 'Alimento Perro Adulto MisterPet',
    category: 'Alimentos',
    petType: 'Perros',
    price: 1990,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 15kg.',
    unit: '15kg',
  },
  {
    name: 'Alimento Perro Adulto MisterPet',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2390,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 20kg.',
    unit: '20',
  },
  {
    name: 'Alimento Perro Adulto MisterPet',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2290,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 20kg.',
    unit: '20',
  },
  {
    name: 'Alimento Perro Adulto Pedigree',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2790,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 21kg.',
    unit: '21kg',
  },
  {
    name: 'Alimento Perro Adulto NextFeed',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2290,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 15kg.',
    unit: '15kg',
  },
  {
    name: 'Alimento Perro Adulto Lager',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2290,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 25kg.',
    unit: '25kg',
  },
  {
    name: 'Alimento Perro Adulto Cápitan',
    category: 'Alimentos',
    petType: 'Perros',
    price: 890,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 10kg.',
    unit: '10kg',
  },
  {
    name: 'Alimento Perro Adulto Cápitan',
    category: 'Alimentos',
    petType: 'Perros',
    price: 890,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 10kg.',
    unit: '10kg',
  },
  {
    name: 'Shampoo Perros',
    category: 'Shampoo',
    petType: 'Perros',
    price: 350,
    emoji: '🛁',
    image: '',
    description: 'Shampoo suave con aloe vera para pelo brillante y suave.',
    unit: '700ml',
  },
  {
    name: 'Collar Ajustable',
    category: 'Accesorios',
    petType: 'Perros',
    price: 350,
    emoji: '🦮',
    image: '',
    description: 'Collar resistente con cierre de seguridad. Varios colores.',
    unit: 'unidad',
  },
  {
    name: 'Alimento Perro Adulto, Raza pequeña Biofresh',
    category: 'Alimentos',
    petType: 'Perros',
    price: 1290,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 2,5kg.',
    unit: '2,5kg',
  },
  {
    name: 'Alimento Perro Adulto, Raza pequeña',
    category: 'Alimentos',
    petType: 'Perros',
    price: 2390,
    emoji: '🐕',
    image: '',
    description: 'Croquetas balanceadas para perros adultos. Bolsa 10kg.',
    unit: '10kg',
  },
  // --- GATOS ---
  {
    name: 'Alimento Gato Adulto specialCat',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 2290,
    emoji: '🐈',
    image: '',
    description: 'Croquetas premium para gatos adultos. Alto contenido proteico.',
    unit: '10kg',
  },
  {
    name: 'Alimento Gato Adulto Castrado specialCat',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 2390,
    emoji: '🐈',
    image: '',
    description: 'Croquetas premium para gatos adultos. Alto contenido proteico.',
    unit: '10kg',
  },
  {
    name: 'Alimento Gato Bebe M-LINE',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 2590,
    emoji: '🐈',
    image: '',
    description: 'Croquetas premium para gatos adultos. Alto contenido proteico.',
    unit: '10kg',
  },
  {
    name: 'Alimento Gato ORIGENS Adulto Castrado',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 2190,
    emoji: '🐈',
    image: '',
    description: 'Croquetas premium para gatos adultos. Alto contenido proteico.',
    unit: '11,1kg',
  },
  {
    name: 'Alimento Gato Raza Castrado',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 1690,
    emoji: '🐈',
    image: '',
    description: 'Croquetas premium para gatos adultos. Alto contenido proteico.',
    unit: '10,1kg',
  },
  {
    name: 'Alimento Gatito',
    category: 'Alimentos',
    petType: 'Gatos',
    price: 2390,
    emoji: '🐱',
    image: '',
    description: 'Fórmula especial para gatitos de 0 a 12 meses.',
    unit: '10kg',
  },
  {
    name: 'Shampoo Gatos',
    category: 'Shampoo',
    petType: 'Gatos',
    price: 290,
    emoji: '✨',
    image: '',
    description: 'Shampoo hipoalergénico especial para la piel sensible felina.',
    unit: '400ml',
  },
  {
    name: 'Juguete con Plumas',
    category: 'Accesorios',
    petType: 'Gatos',
    price: 290,
    emoji: '🪶',
    image: '',
    description: 'Varita interactiva con plumas coloridas para estimulación.',
    unit: 'unidad',
  },
  // --- PECES ---
  {
    name: 'Comida Granulada Peces',
    category: 'Alimentos',
    petType: 'Peces',
    price: 150,
    emoji: '🐠',
    image: '',
    description: 'Gránulos flotantes para peces de agua fría y tropical.',
    unit: '20g',
  },
  {
    name: 'Escamas para Peces',
    category: 'Alimentos',
    petType: 'Peces',
    price: 150,
    emoji: '🐟',
    image: '',
    description: 'Escamas nutritivas con vitaminas y minerales esenciales.',
    unit: '20g',
  },
  // --- CONEJOS ---
  {
    name: 'Alimento Conejo',
    category: 'Alimentos',
    petType: 'Conejos',
    price: 70,
    emoji: '🐰',
    image: '',
    description: 'Mix de pellets con vitamina C y minerales para conejos.',
    unit: '1kg',
  },
  {
    name: 'Viruta para Conejos, cuy',
    category: 'Accesorios',
    petType: 'Conejos',
    price: 320,
    emoji: '🪵',
    image: '',
    description: 'Viruta de madera absorbente y desodorizante. Sin polvo.',
    unit: '500g',
  },
  // --- AVES ---
  {
    name: 'Alpiste para Aves',
    category: 'Alimentos',
    petType: 'Aves',
    price: 210,
    emoji: '🐦',
    image: '',
    description: 'Alpiste limpio y seleccionado, ideal para canarios y jilgueros.',
    unit: '500g',
  },
  {
    name: 'Ración hamster',
    category: 'Alimentos',
    petType: '',
    price: 180,
    emoji: '🦜',
    image: '',
    description: 'Mezcla variada de semillas nutritivas para hasmter.',
    unit: '500g',
  },
];

const pb = new PocketBase('http://127.0.0.1:8090');

async function migrar() {
    console.log("🚀 Iniciando migración...");

    // 2. Autenticarse como administrador (Opcional si las reglas están abiertas)
    // await pb.admins.authWithPassword('tu-email@ejemplo.com', 'tu-password');

    for (const item of products) {
        try {
            await pb.collection('productos').create(item);
            console.log(`✅ Creado: ${item.name}`);
        } catch (err) {
            console.error(`❌ Error en ${item.name}:`, err.data);
        }
    }

    console.log("🏁 ¡Migración terminada!");
}

migrar();